{"type": "error", "data": "Error in Umap", "stack": "Traceback (most recent call last):\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n", "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.", "details": null}
{"type": "error", "data": "Error in Umap", "stack": "Traceback (most recent call last):\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n", "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.", "details": null}
{"type": "error", "data": "Error in Umap", "stack": "Traceback (most recent call last):\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/verbs/graph/layout/methods/umap.py\", line 56, in run\n    return compute_umap_positions(\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/graph/visualization/compute_umap_positions.py\", line 71, in compute_umap_positions\n    ).fit_transform(embedding_vectors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2891, in fit_transform\n    self.fit(X, y, force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/umap/umap_.py\", line 2358, in fit\n    X = check_array(X, dtype=np.float32, accept_sparse=\"csr\", order=\"C\", force_all_finite=force_all_finite)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/sklearn/utils/validation.py\", line 1050, in check_array\n    raise ValueError(msg)\nValueError: Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n", "source": "Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.", "details": null}
{"type": "error", "data": "Error executing verb \"drop\" in create_final_nodes: \"['x', 'y'] not found in axis\"", "stack": "Traceback (most recent call last):\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 410, in _execute_verb\n    result = node.verb.func(**verb_args)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/datashaper/engine/verbs/drop.py\", line 20, in drop\n    output = output.drop(columns=columns)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n", "source": "\"['x', 'y'] not found in axis\"", "details": null}
{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/graphrag/index/run.py\", line 323, in run_pipeline\n    result = await workflow.run(context, callbacks)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 410, in _execute_verb\n    result = node.verb.func(**verb_args)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/datashaper/engine/verbs/drop.py\", line 20, in drop\n    output = output.drop(columns=columns)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/frame.py\", line 5581, in drop\n    return super().drop(\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/generic.py\", line 4788, in drop\n    obj = obj._drop_axis(labels, axis, level=level, errors=errors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/generic.py\", line 4830, in _drop_axis\n    new_axis = axis.drop(labels, errors=errors)\n  File \"/Users/aadi/miniconda3/envs/grag_env/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 7070, in drop\n    raise KeyError(f\"{labels[mask].tolist()} not found in axis\")\nKeyError: \"['x', 'y'] not found in axis\"\n", "source": "\"['x', 'y'] not found in axis\"", "details": null}
